version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - .env
    ports:
    - "5432:5432"
    volumes:
    - postgres-data:/data/postgres
    networks:
    - database

  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    env_file:
      - .env
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - postgres-data:/root/.pgadmin
    networks:
    - database

  caddy:
    container_name: caddy
    env_file:
        - .env
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web

networks:
  database:
    name: oaq-database
  web:
    name: oaq-server

volumes:
  postgres-data:
    name: oaq-postgres
